### ISSUE TITLE
Some Models that work fine in Apply Measures Now, get hung up on model data version

### ISSUE THREAD

**Issue by DavidGoldwasser** [macumber/openstudio-vA3C#14]
I'll add details as I learn more, along with some sample models. I don't think it is related to the size of the models because I ran a 400 space model yesterday. The model I'm having issues with now is probably around 50 spaces.

**Comment by macumber** [comment]
Would be great if you could attach the model

**Comment by DavidGoldwasser** [comment]
Sorry @macumber I thought I attached the link
https://www.dropbox.com/s/47p17z4b1bywdri/AedgK12HvacFanCoilDoas_ASHRAE%20169-2006-5B.osm?dl=0

**Comment by DavidGoldwasser** [comment]
Going to kill this, been running for 3-4 hours after E+ done. Ruby is still crunching away with 12-13% of processor

**Comment by DavidGoldwasser** [comment]
I'm hitting it with this model, which earlier this afternoon worked? For all of these I'm using development build. This model is just 10 zones
https://www.dropbox.com/s/km0tbtumu5uyedw/Office_DOE%20Ref%202004_ASHRAE%20169-2006-5B.osm?dl=0

**Comment by macumber** [comment]
I could not reproduce this using 1.7.0 and the current measure version

**Comment by DavidGoldwasser** [comment]
I'll test it this weekend again with updated measure.

**Comment by DavidGoldwasser** [comment]
Both the school and office run to completion, but just crash on mac when going to results tab. I'll leave pull request open.

**Comment by macumber** [comment]
Thanks @DavidGoldwasser seems Mac specific, I think Larry was having issues on Mac too

**Comment by DavidGoldwasser** [comment]
Still doing this on windows, even though it didn't on mac. I'll re-open this.

**Comment by macumber** [comment]
This slow down seems to be caused by queries on the E+ 8.3 SQLFile taking up to 1000x longer than on the E+ 8.2 SQLFile.

**Comment by macumber** [comment]
![5-15-2015 10-00-39 am](https://cloud.githubusercontent.com/assets/1327850/7656691/48b6da6a-fae9-11e4-820b-d2bbe8751f9b.jpg)

**Comment by macumber** [comment]
To reproduce:
- Checkout v02 branch of https://github.com/macumber/openstudio-vA3C
- Enter into test directory, e.g E:\openstudio-vA3C\ViewData\tests
- Replace ExampleModel.osm with model in dropbox linked above (just delete ExampleModel.osm and replace it)
- Launch test (might want to redirect stdout to log), e.g. ruby -I \openstudio\build\OSCore-prefix\src\OSCore-build\ruby\Release ViewData_Test.rb > 1.7.4.log
- First time test is run, E+ simulation will be run
- Subsequent tests will reuse E+ results

**Comment by macumber** [comment]
Fixed by https://github.com/NREL/OpenStudio/pull/1659.  Now measure takes 92 seconds on this model, produces a 66MB html file.  We may have to improve reporting during run and reduce file size, but this is much better

**Comment by macumber** [comment]
@DavidGoldwasser

**Comment by DavidGoldwasser** [comment]
I'll test this out after I make a fresh build. Hopefully tomorrow. School model isn't very big, surprised it takes that long to run and is that big.

**Comment by DavidGoldwasser** [comment]
@macumber in addition to the 66MB html file, there is 150MB json file. Is that HTML looking to that JSON file for the timeseries data or is the HTML self contained?

I saw somewhere between 2-3 minutes for the measure on my machine, and about 20 seconds for it to display in the OS app, but it is response once it shows.I'll close this but still probably a good idea later to figure out ways to speed it up later on.

**Comment by macumber** [comment]
The HTML is self contained, the only difference between the data in the JSON and HTML is that the JSON is pretty printed (with line endings, tabs, etc).  I'm not sure it is worth writing out the JSON by default since it is so large

**Comment by DavidGoldwasser** [comment]
I'm also wondering if we should default to one zone variable for default arguments. Still let them optionally add 2 and 3rd, but this would make file smaller/quicker.
