### ISSUE TITLE
Add option to read geometry from last idf

### ISSUE THREAD

**Issue by macumber** [macumber/openstudio-vA3C#19]

**Comment by macumber** [comment]
Maybe this should be the default for view data?

**Comment by DavidGoldwasser** [comment]
I tested both, but I agree, using IDF as default seems like what you would normally want. Maybe doesn't need to be an argument?

**Comment by macumber** [comment]
Using OSM preserves space types and interior partitions, IDF would be for if you do E+ changes in measures, does that make sense?
