### ISSUE TITLE
ViewModel measure corrupts model

### ISSUE THREAD

**Issue by shorowit** [macumber/openstudio-vA3C#40]
When I run our [BEopt geometry measure](https://github.com/NREL/OpenStudio-BEopt/tree/master/measures/ResidentialGeometrySingleFamilyDetached) without calling the ViewModel measure, the resulting OSM renders correctly in SketchUp without errors:

![without_view_model](https://cloud.githubusercontent.com/assets/5861765/19526050/58e663f4-95e0-11e6-9c44-1e2fe6538400.png)

But when I call the ViewModel measure right after, I get a SketchUp error as well as a reversed roof surface:

![with_view_model](https://cloud.githubusercontent.com/assets/5861765/19526079/6bbc8616-95e0-11e6-968a-e47014496391.png)

Here are the OSM files produced (rename .txt to .osm):
[without_view_model.txt](https://github.com/macumber/openstudio-vA3C/files/539497/without_view_model.txt)
[with_view_model.txt](https://github.com/macumber/openstudio-vA3C/files/539498/with_view_model.txt)

**Comment by DavidGoldwasser** [comment]
@macumber that is really odd, I didn't think this would touch the model?
